### ISSUE TITLE
docker command

### ISSUE THREAD

**Issue by shubihu** [genome/docker-annotsv-cwl#6]
hi, how to use the annotsv image with docker? what is the command? Thanks

**Comment by tmooney** [comment]
This docker image was created for use in CWL workflows, so the command to run AnnotSV inside looks something like this:
https://github.com/genome/analysis-workflows/blob/eb0092603bf57acb7bda08a06e4f2f1e2a8c9b6d/definitions/tools/annotsv.cwl#L6 (with the other options being filled in from the workflow).

**Comment by shubihu** [comment]
I have soved it, thank you very much!
